name: Style

on:
  push:
    branches: [ "main", "colmap"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install flake
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install flake8-bugbear
        pip install black

    - name: Flake 8 Syntax Errors
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Flake 8 Syntax Warnings
      run: | 
        flake8 . --count --statistics

    - name: Black formatting
      run: |
        black . --check